FROM lmcache/vllm-openai:latest

USER root
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      iproute2 \
      iptables \
      iputils-ping \
      ethtool \
      net-tools && \
    rm -rf /var/lib/apt/lists/*